<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-21 14:51
=======
# Generated by Django 5.2.5 on 2025-08-22 09:52
>>>>>>> 89551485f9bdef703466f04a75b57109cb9a3b07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='created_date',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
